name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/arrow-down-sign-to-navigate-1-1.png
    - assets/page-1/images/icon.png
    - assets/page-1/images/group-23.png
    - assets/page-1/images/group-33.png
    - assets/page-1/images/group-32.png
    - assets/page-1/images/icon-omT.png
    - assets/page-1/images/icon-3Xw.png
    - assets/page-1/images/group-31.png
    - assets/page-1/images/icon-Qad.png
    - assets/page-1/images/group-34.png
    - assets/page-1/images/icon-6mF.png
    - assets/page-1/images/icon-t3T.png
    - assets/page-1/images/icon-ccy.png
    - assets/page-1/images/group-35.png
    - assets/page-1/images/icon-rA5.png
    - assets/page-1/images/icon-tHX.png
    - assets/page-1/images/icon-XnR.png
    - assets/page-1/images/group-30.png
    - assets/page-1/images/arrow-down-sign-to-navigate-1-1-BxV.png
    - assets/page-1/images/arrow-down-sign-to-navigate-1-1-1sX.png
    - assets/page-1/images/user-2.png
    - assets/page-1/images/group-30-GPs.png
    - assets/page-1/images/group-32-acq.png
    - assets/page-1/images/group-35-Syo.png
    - assets/page-1/images/group-30-n25.png
    - assets/page-1/images/group-28.png
    - assets/page-1/images/save-instagram-5.png
    - assets/page-1/images/user-2-tHf.png
    - assets/page-1/images/icon-jjX.png
    - assets/page-1/images/group-31-DHj.png
    - assets/page-1/images/group-32-pbb.png
    - assets/page-1/images/user-1.png
    - assets/page-1/images/save-instagram-4-C89.png
    - assets/page-1/images/save-instagram-2-jmT.png
    - assets/page-1/images/group-34-DXP.png
    - assets/page-1/images/arrow-down-sign-to-navigate-1-1-cFj.png
    - assets/page-1/images/group-28-7Po.png
    - assets/page-1/images/group-31-L3b.png
    - assets/page-1/images/group-32-fjP.png
    - assets/page-1/images/save-instagram-4.png
    - assets/page-1/images/arrow-down-sign-to-navigate-1-1-NNm.png
    - assets/page-1/images/more-1.png
    - assets/page-1/images/save-instagram-6.png
    - assets/page-1/images/arrow-down-sign-to-navigate-1-1-FT7.png
    - assets/page-1/images/save-instagram-1.png
    - assets/page-1/images/save-instagram-2.png
    - assets/page-1/images/save-instagram-1-91s.png
    - assets/page-1/images/save-instagram-2-LyP.png
    - assets/page-1/images/arrow-down-sign-to-navigate-1-1-ywX.png
    - assets/page-1/images/group-33-x6d.png
    - assets/page-1/images/save-instagram-3.png
    - assets/page-1/images/save-instagram-4-4Mw.png
    - assets/page-1/images/save-instagram-3-LEu.png
    - assets/page-1/images/save-instagram-1-UfB.png
    - assets/page-1/images/user-1-Xqj.png
    - assets/page-1/images/save-instagram-5-PFf.png
    - assets/page-1/images/logo.png
    - assets/page-1/images/save-instagram-2-D9T.png
    - assets/page-1/images/check-mark-1.png
    - assets/page-1/images/logo-Akq.png
    - assets/page-1/images/user-2-gNM.png
    - assets/page-1/images/check-mark-1-qwP.png
    - assets/page-1/images/group-34-soX.png
    - assets/page-1/images/save-instagram-5-Hzy.png
    - assets/page-1/images/save-instagram-3-XRT.png
    - assets/page-1/images/save-instagram-3-ho7.png
    - assets/page-1/images/arrow-down-sign-to-navigate-1-1-3c5.png
    - assets/page-1/images/arrow-down-sign-to-navigate-1-1-ot5.png
    - assets/page-1/images/save-instagram-2-MPo.png
    - assets/page-1/images/save-instagram-1-ep9.png
    - assets/page-1/images/group-33-HrR.png
    - assets/page-1/images/save-instagram-6-Hms.png
    - assets/page-1/images/more-1-ipZ.png
    - assets/page-1/images/more-1-U4y.png
    - assets/page-1/images/save-instagram-3-QHP.png
    - assets/page-1/images/save-instagram-5-rMP.png
    - assets/page-1/images/more-1-cLZ.png
    - assets/page-1/images/arrow-down-sign-to-navigate-1-1-BeR.png
    - assets/page-1/images/save-instagram-5-jR3.png
    - assets/page-1/images/more-1-1QV.png
    - assets/page-1/images/save-instagram-5-Zwo.png
    - assets/page-1/images/camera-1.png
    - assets/page-1/images/group-34-7yK.png
    - assets/page-1/images/group-33-tjB.png
    - assets/page-1/images/save-instagram-4-FZj.png
    - assets/page-1/images/save-instagram-6-cv5.png
    - assets/page-1/images/save-instagram-6-Pfw.png
    - assets/page-1/images/group-30-4Bj.png
    - assets/page-1/images/arrow-down-sign-to-navigate-1-1-LS5.png
    - assets/page-1/images/user-2-F3F.png
    - assets/page-1/images/logo-PfF.png
    - assets/page-1/images/save-instagram-1-Z3w.png
    - assets/page-1/images/save-instagram-4-WUy.png
    - assets/page-1/images/group-30-1wX.png
    - assets/page-1/images/arrow-down-sign-to-navigate-1-1-ZTF.png
    - assets/page-1/images/group-34-Jvd.png
    - assets/page-1/images/user-2-T8d.png
    - assets/page-1/images/group-35-Ptm.png
    - assets/page-1/images/image-3.png
    - assets/page-1/images/user-2-C4q.png
    - assets/page-1/images/save-instagram-4-YPb.png
    - assets/page-1/images/logo-K9T.png
    - assets/page-1/images/icon-6bT.png
    - assets/page-1/images/save-instagram-6-LVo.png
    - assets/page-1/images/logo-Wad.png
    - assets/page-1/images/more-1-3VK.png
    - assets/page-1/images/group-31-pd7.png
    - assets/page-1/images/icon-arV.png
    - assets/page-1/images/group-42.png
    - assets/page-1/images/thumbs-up-1.png
    - assets/page-1/images/group-32-Und.png
    - assets/page-1/images/logo-3m3.png
    - assets/page-1/images/group-31-jaZ.png
    - assets/page-1/images/group-35-VLm.png
    - assets/page-1/images/user-2-7sw.png
    - assets/page-1/images/icon-Ti9.png
    - assets/page-1/images/group-35-djX.png
    - assets/page-1/images/user-2-Rz9.png
    - assets/page-1/images/group-30-p2d.png
    - assets/page-1/images/group-31-3KF.png
    - assets/page-1/images/save-instagram-1-72q.png
    - assets/page-1/images/user-2-DxM.png
    - assets/page-1/images/untitleddesign-removebg-preview-1.png
    - assets/page-1/images/save-instagram-3-8rM.png
    - assets/page-1/images/user-2-ii5.png
    - assets/page-1/images/thumbs-up-1-nWu.png
    - assets/page-1/images/logo-pYR.png
    - assets/page-1/images/group-33-UAM.png
    - assets/page-1/images/group-39.png
    - assets/page-1/images/thumbs-up-1-bVs.png
    - assets/page-1/images/image-1.png
    - assets/page-1/images/group-32-umT.png
    - assets/page-1/images/logo-2CR.png
    - assets/page-1/images/logo-8pR.png
    - assets/page-1/images/group-35-4jj.png
    - assets/page-1/images/group-34-N9P.png
    - assets/page-1/images/group-42-hLd.png
    - assets/page-1/images/group-42-YM7.png
    - assets/page-1/images/logo-stV.png
    - assets/page-1/images/untitleddesign-removebg-preview-1-1.png
    - assets/page-1/images/image-2.png
    - assets/page-1/images/group-33-h6Z.png
    - assets/page-1/images/icon-39j.png
    - assets/page-1/images/save-instagram-2-zUh.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
